name: Build

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    
    - name: Build application
      run: make

  tests:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    
    - name: install check
      run: sudo apt-get install check
      
    - name: Build tests
      run: make check

      
