name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    
    - name: Build application
      run: make
      
    - name: Build tests
      run: make check
